### ISSUE TITLE
Redundant Octernship Assignment

### ISSUE THREAD

**Issue by ashwinexe** [appwrite-octernship/engineering-task-2#3]
Previously, Appwrite Octernships assignment were present on the official organization. 
Since this organization has updated and dedicated repos for each assignment keeping the [older repostiory](https://github.com/appwrite/octernships) can confuse students, specially those who applied early during launch and are unaware of updates. The older repository also does not have updated assignments. 

## Solution
I suggest you hide/remove the [Appwrite/Octernship](https://github.com/appwrite/octernships) repository for now and grant access to selected Octerns after the review phase. 
It will help in keeping this organization as single source of truth for Octernships Assignment for all participating students.

**Comment by tessamero** [comment]
No problem, I'll have Christy hide it. Just sent him a message to get it taken care of so I will close this.
